language: go

sudo: required

services:
  - docker

go:
  - "1.11.x"

env:
  - DEP_VERSION="0.5.0" DOCKER_BUILDKIT=1

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure -v

script:
  - go build
  - docker build -t forward-proxy-auth .
  - cd integrationtest && go test