language: go

sudo: required

services:
  - docker

go:
  - "1.11.x"

env:
  - DOCKER_BUILDKIT=1
  - DEP_VERSION="0.5.0"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure -v

script:
  - go build
  - cd test && docker-compose up -d && cd ..
  - go test