version: '3.3'
services:
  forward-proxy-auth:
    image: forward-proxy-auth
    networks:
      - default
    env_file:
      - tmpconfig.env
    volumes:
      - ../default-config.yml:/config.yml:ro
    ports:
      - 8080:8080
  
  ldap-test:
    image: rroemhild/test-openldap
    networks:
      - default
    ports:
      - 389:389
